# Generated by Django 5.1.3 on 2024-11-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fido_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djpasskey',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the device', max_length=255, null=True),
        ),
    ]
